import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  container: {
    paddingTop: 30,
    height: '100%',
    width: '100%',
  },
  containerProduct: {
    backgroundColor: "white",
    padding: 5,
    alignSelf: 'center',
    width: 350,
    height: 350,
    borderRadius: 13,
    shadowColor: "black",
    shadowOffset: {
      width: 200,
      height: 200,
    },
    shadowOpacityColor: 10,
    shadowRadius: 10,
    elevation: 5,
    flexDirection: "row",
  },
  infoContainer: {
    flex: 1,
    marginLeft: 20,
  },
  image: {
    marginRight: 60,
    width: "100%",
    height: "100%",
  },
  viewImage: {
    width: 140,
    height: 140,
  },
  quantidade: {
    marginLeft: 120,
    color: "black",
    fontWeight: "bold",
    fontSize: 19,
    fontFamily: 'Montserrat',
    position: 'absolute',
    bottom: 1,
  },
  descricao: {
    marginTop: 20,
    color: "black",
    fontSize: 25,
    maxHeight: 170,
    fontFamily: 'Montserrat',
    position: 'absolute',
    bottom: 180,
    marginEnd: 10,
  },
  preco: {
    marginVertical: -100,
    color: "black",
    fontSize: 20,
    textAlign: 'center',
    fontWeight: 'bold',
    fontFamily: 'Montserrat',
    position: 'absolute',
    bottom: 135,
    marginLeft: 70,
  },
  headerLeft: {
    marginTop: -10,
    marginLeft: 20,
  },
  texto: {
    width: '95%',
    height: 35,
    borderRadius: 5,
    backgroundColor: 'green',
    marginLeft: 10,
    textAlign: "center",
    color: "black",
    fontSize: 25,
    fontWeight: "bold",
    fontFamily: 'Montserrat',
    position: 'absolute',
    bottom: 15,
  },
});
